### ISSUE TITLE
Map of workloads to Install

### ISSUE THREAD

**Issue by jmarhee** [equinix/terraform-metal-multiarch-k8s#61]
I want to define versions for every optional component, rather than defining this in user data; CCM, CSI driver, etc. Storage and Network can be a part of this; rather than discrete variables, just part of one object that I can select out.

**Comment by displague** [comment]
A similar pattern has emerged in the anthos-on-baremetal module:
https://github.com/equinix/terraform-metal-anthos-on-baremetal/pull/37/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R221-R226

**Comment by displague** [comment]
In this case, storage is a one of many choice. The way that that storage module optional installs each chosen component could be replicated to optionally install many components (from a map variable).

https://github.com/equinix/terraform-metal-anthos-on-baremetal/pull/37/files#diff-1477e73501a9229a6501623ac074d620b1bdc7d056602a7e775f01e8c22e6c4dR2

**Comment by displague** [comment]
The CSI could be made optional, which would fulfill #63
