### ISSUE TITLE
Add the Packet CCM (and swap MetalLB for Kube-VIP)

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-multiarch-k8s#64]
* Install the Packet CCM, this will provide node annotations and will update the cluster on the status of the devices from the Equinix Metal API.
* Swap out MetalLB for Kube-VIP. Kube-VIP can function as the VIP for the cluster API as well as the `type: LoadBalancer` provider for `Service` resources.
* Update the docs, including:
  > This project configures your cluster with:
  > MetalLB using Packet elastic IPs.

**Comment by displague** [comment]
We may want to make cloudprovider=external a toggleable feature.
The CCM and kube-vip would also be optional.

Existing users (that disable the workloads) would be surprised to find these components installed with the external setting enacted.

**Comment by vielmetti** [comment]
@displague @keithmattix - looking at this issue to enable Kubeflow onprem development - you two might be interested in collaborating towards a PR.
