### ISSUE TITLE
Change Calico installation to operator

### ISSUE THREAD

**Issue by DavidSpek** [equinix/terraform-metal-multiarch-k8s#78]
When deploying a cluster with this module we had some problems DNS not working in pods. Changing to the Calico operator installation solved the problem instantly.

This command:
https://github.com/equinix/terraform-metal-multiarch-k8s/blob/efe06f17ada41d44a6e78e96cb29ecdaac2d3a2a/modules/controller_pool/controller-primary.tpl#L67

Would need to be replaced by the following 2 commands:

```bash
kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
```

Source:
https://docs.projectcalico.org/getting-started/kubernetes/quickstart#install-calico

**Comment by jmarhee** [comment]
Addressed in #75
